# æ•´ä¸ªæµç¨‹çš„åå­—
name: CI

# è§¦å‘æ—¶æœºï¼Œåœ¨ main åˆ†æ”¯ push æ“ä½œè§¦å‘
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# ä»»åŠ¡
jobs:
  CIBUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # git config
      - name: Git Config
        run: |
           git config --global user.email "1750263786@qq.com"
           git config --global user.name "UzumakiHan"
      # install
      - name: Install dependencies
        run: |
           npm ci
      
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          release-type: node
          package-name: standard-version
          changelog-types: '[{"type": "chore", "section":"ğŸ« Chores | å…¶ä»–æ›´æ–°", "hidden": false},{"type": "revert", "section":"âª Reverts | å›é€€", "hidden": false},{"type": "feat", "section": "âœ¨ Features | æ–°åŠŸèƒ½", "hidden": false},{"type": "fix", "section": "ğŸ› Bug Fixes | Bug ä¿®å¤", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"ğŸ“ Documentation | æ–‡æ¡£", "hidden": false},{"type": "style", "section":"ğŸ’„ Styles | é£æ ¼", "hidden": false},{"type": "refactor", "section":"ğŸ’„ Styles | é£æ ¼", "hidden": false},{"type": "perf", "section":"âš¡ Performance Improvements | æ€§èƒ½ä¼˜åŒ–", "hidden": false},{"type": "test", "section":"âœ… Tests | æµ‹è¯•", "hidden": false},{"type": "build", "section":"ğŸ‘·â€ Build System | æ„å»º", "hidden": false},{"type": "ci", "section":"ğŸ”§ Continuous Integration | CI é…ç½®", "hidden":false}]' 
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
        
